import * as fs from 'fs';
import { extractVariables } from './parser';
import { getComponentVariablesOutput, getPaletteVariablesOutput, getThemeVariablesOutput } from './output';

const themeVariables = extractVariables('./src/v2/styles/_theme-variables.scss');
const componentVariables = extractVariables('./src/v2/**/*-@(theme|layout).scss', themeVariables);
const paletteVariables = extractVariables('./src/v2/styles/_palette-variables.scss');

const themeVariablesOutput = getThemeVariablesOutput(themeVariables);
const componentVariablesOutput = getComponentVariablesOutput(componentVariables);
const paletteVariablesOutput = getPaletteVariablesOutput(paletteVariables);

const updateAutogeneratedSlot = (
  templateFilePath: string,
  slotId: string,
  contentToInject: string,
  targetFilePath: string,
) => {
  const template = fs.readFileSync(templateFilePath, 'utf8');
  const targetContent = template.replaceAll(slotId, contentToInject);
  fs.writeFileSync(targetFilePath, targetContent, 'utf8');
};

updateAutogeneratedSlot(
  `./doc-templates/palette-variables.template.mdx`,
  `[//]: # '#SLOT-autogenerated-palette-variables'`,
  paletteVariablesOutput,
  `./docs/theming/palette-variables.mdx`,
);

updateAutogeneratedSlot(
  `./doc-templates/theme-variables.template.mdx`,
  `[//]: # '#SLOT-autogenerated-theme-variables'`,
  themeVariablesOutput,
  `./docs/theming/theme-variables.mdx`,
);

updateAutogeneratedSlot(
  `./doc-templates/component-variables.template.mdx`,
  `[//]: # '#SLOT-autogenerated-component-variables'`,
  componentVariablesOutput,
  `./docs/theming/component-variables.mdx`,
);
