import * as fs from 'fs';
import { extractVariables } from './parser';
import { getComponentVariablesOutput, getThemeVariablesOutput } from './output';

const themeVariables = extractVariables('./src/v2/styles/_theme-variables.scss');
const componentVariables = extractVariables('./src/v2/**/*-@(theme|layout).scss', themeVariables);

const themeVariablesOutput = getThemeVariablesOutput(themeVariables);
const componentVariablesOutput = getComponentVariablesOutput(componentVariables);

const updateAutogeneratedSlot = (
  templateFilePath: string,
  slotId: string,
  contentToInject: string,
  targetFilePath: string,
) => {
  const template = fs.readFileSync(templateFilePath, 'utf8');
  const targetContent = template.replaceAll(slotId, contentToInject);
  fs.writeFileSync(targetFilePath, targetContent, 'utf8');
};

updateAutogeneratedSlot(
  `./docs/theming/theme-variables.template.mdx`,
  `[//]: # (#SLOT-autogenerated-theme-variables)`,
  themeVariablesOutput,
  `./docs/theming/theme-variables-2.mdx`,
);

updateAutogeneratedSlot(
  `./docs/theming/component-variables.template.mdx`,
  `[//]: # (#SLOT-autogenerated-component-variables)`,
  componentVariablesOutput,
  `./docs/theming/component-variables-2.mdx`,
);
